<?php

/**
 * @file
 * Install file of the agri_stakeholder feature.
 */

/**
 * Implements hook_enable().
 */
function agri_stakeholder_enable() {
  $t = get_t();
  drupal_set_message($t('AGRI Stakeholder feature is now active on your site.'));
}

/**
 * Implements hook_disable().
 */
function agri_stakeholder_disable() {
  $t = get_t();
  drupal_set_message($t('AGRI Stakeholder feature is now inactive on your site.'));
}
