---
kind: pipeline
name: agri-eip

platform:
  os: linux
  arch: amd64

# SERVICES #
services:
  - name: web
    image: fpfis/php56-build
    environment:
      DOCUMENT_ROOT: /test/toolkit/build
      PORT: 8080
      # TEST CUSTOM SECRETS.
      test_user:
        from_secret: test_user
      test_password:
        from_secret: test_password
    commands:
      - echo test_user
      - echo test.password



