---
kind: pipeline
name: enrd

platform:
  os: linux
  arch: amd64

# GIT CLONE SECTION #
git-clone:
  git:
    image: plugins/git:next

# WORKSPACE #
workspace:
  base: /test
  path: toolkit

# SERVICES #
services:
  - name: web
    image: fpfis/php56-build
    environment:
      DOCUMENT_ROOT: /test/toolkit/build
      PORT: 8080

# BUILD SECTION #
steps:
  # SETUP TOOLKIT #
  - name: toolkit
    image: fpfis/php56-dev
    commands:
      - composer install
      - rm -rf ./.tmp/ ./build
      # - cp ./vendor/ec-europa/toolkit/includes/phing/props/drone.props build.develop.props
      - ./toolkit/phing project-properties-validate

# TELEGRAM NOTIFICATIONS
  - name: notification
    image: appleboy/drone-telegram
    settings:
      token: 1010031050:AAFiKD77-RBdVB9BKQMRFmHypOGuz1ACa9k
      to: @alessiodepisi
      message: >
        {{#success build.status}}
          build succeeded. Good job.
        {{else}}
          build failed. Fix me please.
        {{/success}}