---
kind: pipeline
name: enrd

platform:
  os: linux
  arch: amd64

# GIT CLONE SECTION #
git-clone:
  git:
    image: plugins/git:next

# WORKSPACE #
workspace:
  base: /test
  path: toolkit

# SERVICES #
services:
  - name: web
    image: fpfis/php56-build
    environment:
      DOCUMENT_ROOT: /test/toolkit/build
      PORT: 8080

  - name: mysql
    image: fpfis/mysql56
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_MAX_ALLOWED_PACKET: 128M

# BUILD SECTION #
steps:
  # SETUP TOOLKIT #
  - name: toolkit
    image: fpfis/php56-dev
    commands:
      - composer install
      - rm -rf ./.tmp/ ./build
      # - cp ./vendor/ec-europa/toolkit/includes/phing/props/drone.props build.develop.props
      - ./toolkit/phing project-properties-validate

  # PHPCS CHECKS #
  # Standard #
    # - name: phpcs
    # image: fpfis/php56-dev
      # commands:
      # - ./toolkit/phing test-run-phpcs

  # BUILD PLATFORM AND SUBSITE#
  - name: build
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing build-platform build-subsite-dev

  # SOLR SERVER SECTION #
  - name: solr
    image: fpfis/solr5
    detach: true

  # INSTALL SECTION #
  # CLEAN #
  - name: install-clean
    image: fpfis/php56-dev
    commands:
      - rm /test/toolkit/build/sites/sites.php
      - ./toolkit/phing install-clean
      - ./toolkit/phing drush-solr-enable

  # TEST SECTION #
  # SELENIUM #
  - name: selenium
    image: selenium/standalone-chrome-debug
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"
    detach: true

  # BEHAT #
  - name: behat
    image: ffpfis/php56-dev
    commands:
      - ./toolkit/phing test-run-behat