---
kind: pipeline
name: enrd

platform:
  os: linux
  arch: amd64

# GIT CLONE SECTION #
git-clone:
  git:
    image: plugins/git:next

# WORKSPACE #
workspace:
  base: /test
  path: toolkit

# SERVICES #
services:
  - name: web
    image: fpfis/httpd-php:7.3
    environment:
      DOCUMENT_ROOT: /test/toolkit/build
      PORT: 8080

  - name: mysql
    image: percona/percona-server:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_MAX_ALLOWED_PACKET: 128M

# BUILD SECTION #
steps:
  # SETUP TOOLKIT #
  - name: toolkit
    image: fpfis/httpd-php-dev:7.3
    commands:
      - composer install
      - rm -rf ./.tmp/ ./build
      - ./toolkit/phing project-properties-validate

# PHPCS CHECKS
  # Standards
  - name: phpcs
    image: fpfis/httpd-php-dev:7.3
    commands:
      - ./toolkit/phing test-run-phpcs
  # PHP 7 Compatibility
  - name: phpcs 7
    image: fpfis/httpd-php-dev:7.3
    commands:
      - ./toolkit/phing test-run-phpcs-compatibility

  # BUILD PLATFORM AND SUBSITE #
  - name: build
    image: fpfis/httpd-php-dev:7.3
    commands:
      - ./toolkit/phing build-platform build-subsite-dev

  # SOLR SERVER SECTION #
  - name: solr
    image: wodby/solr:7
      environment:
        SOLR_DEFAULT_CONFIG_SET: "search_api_solr_7.x-1.14"
        SOLR_HEAP: 1024m
      ports:
        - "8983:8983"
    detach: true

  # INSTALL SECTION #
  # CLEAN #
  - name: install-clean
    image: fpfis/httpd-php-dev:7.3
    commands:
      - rm /test/toolkit/build/sites/sites.php
      - ./toolkit/phing install-clean
      - ./toolkit/phing drush-solr-enable

  # TEST SECTION #
  # SELENIUM #
  - name: selenium
    image: selenium/standalone-chrome:3.141.59
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"
    detach: true

  # BEHAT #
  - name: behat
    image: fpfis/httpd-php-dev:7.3
    commands:
      - ./toolkit/phing test-run-behat

  # TELEGRAM NOTIFICATIONS
  - name: notification
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
      message: >
        {{#success build.status}}
          ✅ Build succeeded #{{build.number}} of '{{repo.name}}' - Good job!
          Commit by {{commit.author}} on {{commit.branch}}
        {{else}}
          ❌ Build failed #{{build.number}} of '{{repo.name}}' - Fix it please.
          Commit by {{commit.author}} on {{commit.branch}}
        {{/success}}
