---
kind: pipeline
name: enrd

platform:
  os: linux
  arch: amd64

# GIT CLONE SECTION #
git-clone:
  git:
    image: plugins/git:next

# WORKSPACE #
workspace:
  base: /test
  path: toolkit

# SERVICES #
services:
  - name: web
    image: fpfis/httpd-php:7.3
    environment:
      DOCUMENT_ROOT: /test/toolkit/build
      PORT: 8080

  - name: mysql
    image: fpfis/mysql56
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_MAX_ALLOWED_PACKET: 128M

# BUILD SECTION #
steps:
  # SETUP TOOLKIT #
  - name: toolkit
    image: fpfis/httpd-php-dev:7.3
    commands:
      - composer install
      - rm -rf ./.tmp/ ./build
      - ./toolkit/phing project-properties-validate

# PHPCS CHECKS #
# Standard #
  - name: phpcs
     image: fpfis/httpd-php-dev:7.3
     commands:
      - ./toolkit/phing test-run-phpcs

# PHP 7 Compatibility #
  - name: phpcs
      image: fpfis/httpd-php-dev:7.3
      commands:
        - ./toolkit/phing test-run-phpcs-compatibility

  # BUILD PLATFORM AND SUBSITE#
  - name: build
    image: fpfis/httpd-php-dev:7.3
    commands:
      - ./toolkit/phing build-platform build-subsite-dev

  # TELEGRAM NOTIFICATIONS
  - name: notification
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
      message: >
        {{#success build.status}}
          ✅ Build succeeded #{{build.number}} of '{{repo.name}}' - Good job!
          Commit by {{commit.author}} on {{commit.branch}}
        {{else}}
          ❌ Build failed #{{build.number}} of '{{repo.name}}' - Fix it please.
          Commit by {{commit.author}} on {{commit.branch}}
        {{/success}}
