---
kind: pipeline
name: agri-eip

  - name: test-secrets
    image: fpfis/php56-dev
    environment:
      DB.DL.USERNAME:
        from_secret: agri_db_dl_username
      DB.DL.PASSWORD:
        from_secret: agri_db_dl_password
    commands:
      - echo DB.DL.USERNAME
      - echo DB.DL.PASSWORD
