<?php

/**
 * @file
 * Install, update and uninstall functions for the ENRD Gallery.
 */

/**
 * Implements hook_enable().
 */
function enrd_gallery_enable() {
  $t = get_t();
  drupal_set_message($t('ENRD Gallery is now active on your site.'));
}

/**
 * Implements hook_disable().
 */
function enrd_gallery_disable() {
  $t = get_t();
  drupal_set_message($t('ENRD Gallery has been deactivated on your site.'));
}
