version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: fpfis/httpd-php-dev:7.3 # ...with this image as the primary container; this is where all `steps` will run
        name: web
        environment:
          DOCUMENT_ROOT: /test/toolkit/build
          PORT: 8080

      - image: fpfis/mysql56
        name: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_MAX_ALLOWED_PACKET: 128M

      - image: fpfis/solr5
        name: solr
        detach: true

      - image: selenium/standalone-chrome:3.141.59-oxygen
        name: selenium
        environment:
          HUB_PORT_4444_TCP_ADDR: selenium
          HUB_PORT_4444_TCP_PORT: "4444"
        detach: true

    working_directory: /test/toolkit/build # directory where steps will run
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: toolkit
          command: |
              composer install
              rm -rf ./.tmp/ ./build
              ./toolkit/phing project-properties-validate
      - run:
          name: phpcs
          command: ./toolkit/phing test-run-phpcs
      - run:
          name: phpcs-compatibility
          command: ./toolkit/phing test-run-phpcs-compatibility
      - run:
          name: build
          command: ./toolkit/phing build-platform build-subsite-dev
      - run:
          name: install-clean
          command: ./toolkit/phing install-clean
      - run:
          name: behat
          command: ./toolkit/phing test-run-behat

workflows:
  version: 2
  install-clean:
    jobs:
      - build
