<?php

/**
 * @file
 * Install, uninstall and update functions for the AGRI Digitisation Toolbox.
 */

/**
 * Implements hook_enable().
 */
function agri_digitization_toolbox_enable() {
  $t = get_t();
  drupal_set_message($t('Agri Digitization Toolbox feature is now active on your site.'));
}

/**
 * Implements hook_disable().
 */
function agri_digitization_toolbox_disable() {
  $t = get_t();
  drupal_set_message($t('Agri Digitization Toolbox feature is now inactive on your site.'));
}
