<?php

/**
 * @file
 * Code for the AGRI Press Releases feature.
 */

include_once 'agri_press.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function agri_projects_form_press_release_node_form_alter(&$form, &$form_state, $form_id) {
  $form['body'][LANGUAGE_NONE][0]['#title'] = 'Description';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function agri_projects_form_press_clipping_node_form_alter(&$form, &$form_state, $form_id) {
  $form['body'][LANGUAGE_NONE][0]['#title'] = 'Description';
}
